services:
  pos-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pos-web
    restart: always
    networks:
      - shared-network

networks:
  shared-network:
    external: true
